// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Usa URL direta (sem pooler) para migrations — evita advisory lock issue do Neon
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
